org.benf.cfr.reader.util.CannotLoadClassException: net/minecraft/world/entity/LivingEntity.class - java.lang.ArrayIndexOutOfBoundsException
	at org.benf.cfr.reader.state.DCCommonState.loadClassFileAtPath(DCCommonState.java:122)
	at org.benf.cfr.reader.state.DCCommonState$3.invoke(DCCommonState.java:85)
	at org.benf.cfr.reader.state.DCCommonState$3.invoke(DCCommonState.java:82)
	at org.benf.cfr.reader.util.collections.LazyMap.get(LazyMap.java:44)
	at org.benf.cfr.reader.util.collections.LazyExceptionRetainingMap.get(LazyExceptionRetainingMap.java:19)
	at org.benf.cfr.reader.state.DCCommonState.getClassFile(DCCommonState.java:183)
	at org.benf.cfr.reader.state.DCCommonState.getClassFileMaybePath(DCCommonState.java:219)
	at cuchaz.enigma.source.cfr.CfrSource.ensureDecompiled(CfrSource.java:62)
	at cuchaz.enigma.source.cfr.CfrSource.asString(CfrSource.java:50)
	at cuchaz.enigma.EnigmaProject$JarExport.decompileClass(EnigmaProject.java:298)
	at cuchaz.enigma.EnigmaProject$JarExport.lambda$decompileStream$1(EnigmaProject.java:274)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:722)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1311)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1840)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1806)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: java.lang.ArrayIndexOutOfBoundsException
