/*
 * Decompiled with CFR 0.1.0 (FabricMC a830a72d).
 * 
 * Could not load the following classes:
 *  com.mojang.datafixers.util.Pair
 *  java.lang.IllegalArgumentException
 *  java.lang.Object
 *  java.lang.String
 *  java.util.Collection
 *  java.util.EnumSet
 *  java.util.HashMap
 *  java.util.List
 *  java.util.Set
 *  java.util.function.Supplier
 *  javax.annotation.Nullable
 */
package net.minecraft.world.item;

import com.mojang.datafixers.util.Pair;
import java.util.Collection;
import java.util.EnumSet;
import java.util.HashMap;
import java.util.List;
import java.util.Set;
import java.util.function.Supplier;
import javax.annotation.Nullable;
import net.minecraft.core.Holder;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.network.chat.Component;
import net.minecraft.tags.InstrumentTags;
import net.minecraft.tags.TagKey;
import net.minecraft.world.entity.raid.Raid;
import net.minecraft.world.flag.FeatureFlagSet;
import net.minecraft.world.flag.FeatureFlags;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.EnchantedBookItem;
import net.minecraft.world.item.FireworkRocketItem;
import net.minecraft.world.item.Instrument;
import net.minecraft.world.item.InstrumentItem;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.ItemStackLinkedSet;
import net.minecraft.world.item.Items;
import net.minecraft.world.item.SuspiciousStewItem;
import net.minecraft.world.item.alchemy.Potion;
import net.minecraft.world.item.alchemy.PotionUtils;
import net.minecraft.world.item.alchemy.Potions;
import net.minecraft.world.item.enchantment.Enchantment;
import net.minecraft.world.item.enchantment.EnchantmentCategory;
import net.minecraft.world.item.enchantment.EnchantmentInstance;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.block.LightBlock;
import net.minecraft.world.level.block.SuspiciousEffectHolder;

public class CreativeModeTabs {
    private static final CreativeModeTab BUILDING_BLOCKS = CreativeModeTab.builder(CreativeModeTab.Row.TOP, 0).title(Component.translatable("itemGroup.buildingBlocks")).icon((Supplier<ItemStack>)((Supplier)() -> new ItemStack(Blocks.BRICKS))).displayItems(($$0, $$1, $$2) -> {
        $$1.accept(Items.OAK_LOG);
        $$1.accept(Items.OAK_WOOD);
        $$1.accept(Items.STRIPPED_OAK_LOG);
        $$1.accept(Items.STRIPPED_OAK_WOOD);
        $$1.accept(Items.OAK_PLANKS);
        $$1.accept(Items.OAK_STAIRS);
        $$1.accept(Items.OAK_SLAB);
        $$1.accept(Items.OAK_FENCE);
        $$1.accept(Items.OAK_FENCE_GATE);
        $$1.accept(Items.OAK_DOOR);
        $$1.accept(Items.OAK_TRAPDOOR);
        $$1.accept(Items.OAK_PRESSURE_PLATE);
        $$1.accept(Items.OAK_BUTTON);
        $$1.accept(Items.SPRUCE_LOG);
        $$1.accept(Items.SPRUCE_WOOD);
        $$1.accept(Items.STRIPPED_SPRUCE_LOG);
        $$1.accept(Items.STRIPPED_SPRUCE_WOOD);
        $$1.accept(Items.SPRUCE_PLANKS);
        $$1.accept(Items.SPRUCE_STAIRS);
        $$1.accept(Items.SPRUCE_SLAB);
        $$1.accept(Items.SPRUCE_FENCE);
        $$1.accept(Items.SPRUCE_FENCE_GATE);
        $$1.accept(Items.SPRUCE_DOOR);
        $$1.accept(Items.SPRUCE_TRAPDOOR);
        $$1.accept(Items.SPRUCE_PRESSURE_PLATE);
        $$1.accept(Items.SPRUCE_BUTTON);
        $$1.accept(Items.BIRCH_LOG);
        $$1.accept(Items.BIRCH_WOOD);
        $$1.accept(Items.STRIPPED_BIRCH_LOG);
        $$1.accept(Items.STRIPPED_BIRCH_WOOD);
        $$1.accept(Items.BIRCH_PLANKS);
        $$1.accept(Items.BIRCH_STAIRS);
        $$1.accept(Items.BIRCH_SLAB);
        $$1.accept(Items.BIRCH_FENCE);
        $$1.accept(Items.BIRCH_FENCE_GATE);
        $$1.accept(Items.BIRCH_DOOR);
        $$1.accept(Items.BIRCH_TRAPDOOR);
        $$1.accept(Items.BIRCH_PRESSURE_PLATE);
        $$1.accept(Items.BIRCH_BUTTON);
        $$1.accept(Items.JUNGLE_LOG);
        $$1.accept(Items.JUNGLE_WOOD);
        $$1.accept(Items.STRIPPED_JUNGLE_LOG);
        $$1.accept(Items.STRIPPED_JUNGLE_WOOD);
        $$1.accept(Items.JUNGLE_PLANKS);
        $$1.accept(Items.JUNGLE_STAIRS);
        $$1.accept(Items.JUNGLE_SLAB);
        $$1.accept(Items.JUNGLE_FENCE);
        $$1.accept(Items.JUNGLE_FENCE_GATE);
        $$1.accept(Items.JUNGLE_DOOR);
        $$1.accept(Items.JUNGLE_TRAPDOOR);
        $$1.accept(Items.JUNGLE_PRESSURE_PLATE);
        $$1.accept(Items.JUNGLE_BUTTON);
        $$1.accept(Items.ACACIA_LOG);
        $$1.accept(Items.ACACIA_WOOD);
        $$1.accept(Items.STRIPPED_ACACIA_LOG);
        $$1.accept(Items.STRIPPED_ACACIA_WOOD);
        $$1.accept(Items.ACACIA_PLANKS);
        $$1.accept(Items.ACACIA_STAIRS);
        $$1.accept(Items.ACACIA_SLAB);
        $$1.accept(Items.ACACIA_FENCE);
        $$1.accept(Items.ACACIA_FENCE_GATE);
        $$1.accept(Items.ACACIA_DOOR);
        $$1.accept(Items.ACACIA_TRAPDOOR);
        $$1.accept(Items.ACACIA_PRESSURE_PLATE);
        $$1.accept(Items.ACACIA_BUTTON);
        $$1.accept(Items.DARK_OAK_LOG);
        $$1.accept(Items.DARK_OAK_WOOD);
        $$1.accept(Items.STRIPPED_DARK_OAK_LOG);
        $$1.accept(Items.STRIPPED_DARK_OAK_WOOD);
        $$1.accept(Items.DARK_OAK_PLANKS);
        $$1.accept(Items.DARK_OAK_STAIRS);
        $$1.accept(Items.DARK_OAK_SLAB);
        $$1.accept(Items.DARK_OAK_FENCE);
        $$1.accept(Items.DARK_OAK_FENCE_GATE);
        $$1.accept(Items.DARK_OAK_DOOR);
        $$1.accept(Items.DARK_OAK_TRAPDOOR);
        $$1.accept(Items.DARK_OAK_PRESSURE_PLATE);
        $$1.accept(Items.DARK_OAK_BUTTON);
        $$1.accept(Items.MANGROVE_LOG);
        $$1.accept(Items.MANGROVE_WOOD);
        $$1.accept(Items.STRIPPED_MANGROVE_LOG);
        $$1.accept(Items.STRIPPED_MANGROVE_WOOD);
        $$1.accept(Items.MANGROVE_PLANKS);
        $$1.accept(Items.MANGROVE_STAIRS);
        $$1.accept(Items.MANGROVE_SLAB);
        $$1.accept(Items.MANGROVE_FENCE);
        $$1.accept(Items.MANGROVE_FENCE_GATE);
        $$1.accept(Items.MANGROVE_DOOR);
        $$1.accept(Items.MANGROVE_TRAPDOOR);
        $$1.accept(Items.MANGROVE_PRESSURE_PLATE);
        $$1.accept(Items.MANGROVE_BUTTON);
        $$1.accept(Items.BAMBOO_BLOCK);
        $$1.accept(Items.STRIPPED_BAMBOO_BLOCK);
        $$1.accept(Items.BAMBOO_PLANKS);
        $$1.accept(Items.BAMBOO_MOSAIC);
        $$1.accept(Items.BAMBOO_STAIRS);
        $$1.accept(Items.BAMBOO_MOSAIC_STAIRS);
        $$1.accept(Items.BAMBOO_SLAB);
        $$1.accept(Items.BAMBOO_MOSAIC_SLAB);
        $$1.accept(Items.BAMBOO_FENCE);
        $$1.accept(Items.BAMBOO_FENCE_GATE);
        $$1.accept(Items.BAMBOO_DOOR);
        $$1.accept(Items.BAMBOO_TRAPDOOR);
        $$1.accept(Items.BAMBOO_PRESSURE_PLATE);
        $$1.accept(Items.BAMBOO_BUTTON);
        $$1.accept(Items.CRIMSON_STEM);
        $$1.accept(Items.CRIMSON_HYPHAE);
        $$1.accept(Items.STRIPPED_CRIMSON_STEM);
        $$1.accept(Items.STRIPPED_CRIMSON_HYPHAE);
        $$1.accept(Items.CRIMSON_PLANKS);
        $$1.accept(Items.CRIMSON_STAIRS);
        $$1.accept(Items.CRIMSON_SLAB);
        $$1.accept(Items.CRIMSON_FENCE);
        $$1.accept(Items.CRIMSON_FENCE_GATE);
        $$1.accept(Items.CRIMSON_DOOR);
        $$1.accept(Items.CRIMSON_TRAPDOOR);
        $$1.accept(Items.CRIMSON_PRESSURE_PLATE);
        $$1.accept(Items.CRIMSON_BUTTON);
        $$1.accept(Items.WARPED_STEM);
        $$1.accept(Items.WARPED_HYPHAE);
        $$1.accept(Items.STRIPPED_WARPED_STEM);
        $$1.accept(Items.STRIPPED_WARPED_HYPHAE);
        $$1.accept(Items.WARPED_PLANKS);
        $$1.accept(Items.WARPED_STAIRS);
        $$1.accept(Items.WARPED_SLAB);
        $$1.accept(Items.WARPED_FENCE);
        $$1.accept(Items.WARPED_FENCE_GATE);
        $$1.accept(Items.WARPED_DOOR);
        $$1.accept(Items.WARPED_TRAPDOOR);
        $$1.accept(Items.WARPED_PRESSURE_PLATE);
        $$1.accept(Items.WARPED_BUTTON);
        $$1.accept(Items.STONE);
        $$1.accept(Items.STONE_STAIRS);
        $$1.accept(Items.STONE_SLAB);
        $$1.accept(Items.STONE_PRESSURE_PLATE);
        $$1.accept(Items.STONE_BUTTON);
        $$1.accept(Items.COBBLESTONE);
        $$1.accept(Items.COBBLESTONE_STAIRS);
        $$1.accept(Items.COBBLESTONE_SLAB);
        $$1.accept(Items.COBBLESTONE_WALL);
        $$1.accept(Items.MOSSY_COBBLESTONE);
        $$1.accept(Items.MOSSY_COBBLESTONE_STAIRS);
        $$1.accept(Items.MOSSY_COBBLESTONE_SLAB);
        $$1.accept(Items.MOSSY_COBBLESTONE_WALL);
        $$1.accept(Items.SMOOTH_STONE);
        $$1.accept(Items.SMOOTH_STONE_SLAB);
        $$1.accept(Items.STONE_BRICKS);
        $$1.accept(Items.CRACKED_STONE_BRICKS);
        $$1.accept(Items.STONE_BRICK_STAIRS);
        $$1.accept(Items.STONE_BRICK_SLAB);
        $$1.accept(Items.STONE_BRICK_WALL);
        $$1.accept(Items.CHISELED_STONE_BRICKS);
        $$1.accept(Items.MOSSY_STONE_BRICKS);
        $$1.accept(Items.MOSSY_STONE_BRICK_STAIRS);
        $$1.accept(Items.MOSSY_STONE_BRICK_SLAB);
        $$1.accept(Items.MOSSY_STONE_BRICK_WALL);
        $$1.accept(Items.GRANITE);
        $$1.accept(Items.GRANITE_STAIRS);
        $$1.accept(Items.GRANITE_SLAB);
        $$1.accept(Items.GRANITE_WALL);
        $$1.accept(Items.POLISHED_GRANITE);
        $$1.accept(Items.POLISHED_GRANITE_STAIRS);
        $$1.accept(Items.POLISHED_GRANITE_SLAB);
        $$1.accept(Items.DIORITE);
        $$1.accept(Items.DIORITE_STAIRS);
        $$1.accept(Items.DIORITE_SLAB);
        $$1.accept(Items.DIORITE_WALL);
        $$1.accept(Items.POLISHED_DIORITE);
        $$1.accept(Items.POLISHED_DIORITE_STAIRS);
        $$1.accept(Items.POLISHED_DIORITE_SLAB);
        $$1.accept(Items.ANDESITE);
        $$1.accept(Items.ANDESITE_STAIRS);
        $$1.accept(Items.ANDESITE_SLAB);
        $$1.accept(Items.ANDESITE_WALL);
        $$1.accept(Items.POLISHED_ANDESITE);
        $$1.accept(Items.POLISHED_ANDESITE_STAIRS);
        $$1.accept(Items.POLISHED_ANDESITE_SLAB);
        $$1.accept(Items.DEEPSLATE);
        $$1.accept(Items.COBBLED_DEEPSLATE);
        $$1.accept(Items.COBBLED_DEEPSLATE_STAIRS);
        $$1.accept(Items.COBBLED_DEEPSLATE_SLAB);
        $$1.accept(Items.COBBLED_DEEPSLATE_WALL);
        $$1.accept(Items.CHISELED_DEEPSLATE);
        $$1.accept(Items.POLISHED_DEEPSLATE);
        $$1.accept(Items.POLISHED_DEEPSLATE_STAIRS);
        $$1.accept(Items.POLISHED_DEEPSLATE_SLAB);
        $$1.accept(Items.POLISHED_DEEPSLATE_WALL);
        $$1.accept(Items.DEEPSLATE_BRICKS);
        $$1.accept(Items.CRACKED_DEEPSLATE_BRICKS);
        $$1.accept(Items.DEEPSLATE_BRICK_STAIRS);
        $$1.accept(Items.DEEPSLATE_BRICK_SLAB);
        $$1.accept(Items.DEEPSLATE_BRICK_WALL);
        $$1.accept(Items.DEEPSLATE_TILES);
        $$1.accept(Items.CRACKED_DEEPSLATE_TILES);
        $$1.accept(Items.DEEPSLATE_TILE_STAIRS);
        $$1.accept(Items.DEEPSLATE_TILE_SLAB);
        $$1.accept(Items.DEEPSLATE_TILE_WALL);
        $$1.accept(Items.REINFORCED_DEEPSLATE);
        $$1.accept(Items.BRICKS);
        $$1.accept(Items.BRICK_STAIRS);
        $$1.accept(Items.BRICK_SLAB);
        $$1.accept(Items.BRICK_WALL);
        $$1.accept(Items.PACKED_MUD);
        $$1.accept(Items.MUD_BRICKS);
        $$1.accept(Items.MUD_BRICK_STAIRS);
        $$1.accept(Items.MUD_BRICK_SLAB);
        $$1.accept(Items.MUD_BRICK_WALL);
        $$1.accept(Items.SANDSTONE);
        $$1.accept(Items.SANDSTONE_STAIRS);
        $$1.accept(Items.SANDSTONE_SLAB);
        $$1.accept(Items.SANDSTONE_WALL);
        $$1.accept(Items.CHISELED_SANDSTONE);
        $$1.accept(Items.SMOOTH_SANDSTONE);
        $$1.accept(Items.SMOOTH_SANDSTONE_STAIRS);
        $$1.accept(Items.SMOOTH_SANDSTONE_SLAB);
        $$1.accept(Items.CUT_SANDSTONE);
        $$1.accept(Items.CUT_STANDSTONE_SLAB);
        $$1.accept(Items.RED_SANDSTONE);
        $$1.accept(Items.RED_SANDSTONE_STAIRS);
        $$1.accept(Items.RED_SANDSTONE_SLAB);
        $$1.accept(Items.RED_SANDSTONE_WALL);
        $$1.accept(Items.CHISELED_RED_SANDSTONE);
        $$1.accept(Items.SMOOTH_RED_SANDSTONE);
        $$1.accept(Items.SMOOTH_RED_SANDSTONE_STAIRS);
        $$1.accept(Items.SMOOTH_RED_SANDSTONE_SLAB);
        $$1.accept(Items.CUT_RED_SANDSTONE);
        $$1.accept(Items.CUT_RED_SANDSTONE_SLAB);
        $$1.accept(Items.SEA_LANTERN);
        $$1.accept(Items.PRISMARINE);
        $$1.accept(Items.PRISMARINE_STAIRS);
        $$1.accept(Items.PRISMARINE_SLAB);
        $$1.accept(Items.PRISMARINE_WALL);
        $$1.accept(Items.PRISMARINE_BRICKS);
        $$1.accept(Items.PRISMARINE_BRICK_STAIRS);
        $$1.accept(Items.PRISMARINE_BRICK_SLAB);
        $$1.accept(Items.DARK_PRISMARINE);
        $$1.accept(Items.DARK_PRISMARINE_STAIRS);
        $$1.accept(Items.DARK_PRISMARINE_SLAB);
        $$1.accept(Items.NETHERRACK);
        $$1.accept(Items.NETHER_BRICKS);
        $$1.accept(Items.CRACKED_NETHER_BRICKS);
        $$1.accept(Items.NETHER_BRICK_STAIRS);
        $$1.accept(Items.NETHER_BRICK_SLAB);
        $$1.accept(Items.NETHER_BRICK_WALL);
        $$1.accept(Items.NETHER_BRICK_FENCE);
        $$1.accept(Items.CHISELED_NETHER_BRICKS);
        $$1.accept(Items.RED_NETHER_BRICKS);
        $$1.accept(Items.RED_NETHER_BRICK_STAIRS);
        $$1.accept(Items.RED_NETHER_BRICK_SLAB);
        $$1.accept(Items.RED_NETHER_BRICK_WALL);
        $$1.accept(Items.BASALT);
        $$1.accept(Items.SMOOTH_BASALT);
        $$1.accept(Items.POLISHED_BASALT);
        $$1.accept(Items.BLACKSTONE);
        $$1.accept(Items.GILDED_BLACKSTONE);
        $$1.accept(Items.BLACKSTONE_STAIRS);
        $$1.accept(Items.BLACKSTONE_SLAB);
        $$1.accept(Items.BLACKSTONE_WALL);
        $$1.accept(Items.CHISELED_POLISHED_BLACKSTONE);
        $$1.accept(Items.POLISHED_BLACKSTONE);
        $$1.accept(Items.POLISHED_BLACKSTONE_STAIRS);
        $$1.accept(Items.POLISHED_BLACKSTONE_SLAB);
        $$1.accept(Items.POLISHED_BLACKSTONE_WALL);
        $$1.accept(Items.POLISHED_BLACKSTONE_PRESSURE_PLATE);
        $$1.accept(Items.POLISHED_BLACKSTONE_BUTTON);
        $$1.accept(Items.POLISHED_BLACKSTONE_BRICKS);
        $$1.accept(Items.CRACKED_POLISHED_BLACKSTONE_BRICKS);
        $$1.accept(Items.POLISHED_BLACKSTONE_BRICK_STAIRS);
        $$1.accept(Items.POLISHED_BLACKSTONE_BRICK_SLAB);
        $$1.accept(Items.POLISHED_BLACKSTONE_BRICK_WALL);
        $$1.accept(Items.END_STONE);
        $$1.accept(Items.END_STONE_BRICKS);
        $$1.accept(Items.END_STONE_BRICK_STAIRS);
        $$1.accept(Items.END_STONE_BRICK_SLAB);
        $$1.accept(Items.END_STONE_BRICK_WALL);
        $$1.accept(Items.PURPUR_BLOCK);
        $$1.accept(Items.PURPUR_PILLAR);
        $$1.accept(Items.PURPUR_STAIRS);
        $$1.accept(Items.PURPUR_SLAB);
        $$1.accept(Items.COAL_BLOCK);
        $$1.accept(Items.IRON_BLOCK);
        $$1.accept(Items.IRON_BARS);
        $$1.accept(Items.IRON_DOOR);
        $$1.accept(Items.IRON_TRAPDOOR);
        $$1.accept(Items.HEAVY_WEIGHTED_PRESSURE_PLATE);
        $$1.accept(Items.CHAIN);
        $$1.accept(Items.GOLD_BLOCK);
        $$1.accept(Items.LIGHT_WEIGHTED_PRESSURE_PLATE);
        $$1.accept(Items.REDSTONE_BLOCK);
        $$1.accept(Items.EMERALD_BLOCK);
        $$1.accept(Items.LAPIS_BLOCK);
        $$1.accept(Items.DIAMOND_BLOCK);
        $$1.accept(Items.NETHERITE_BLOCK);
        $$1.accept(Items.QUARTZ_BLOCK);
        $$1.accept(Items.QUARTZ_STAIRS);
        $$1.accept(Items.QUARTZ_SLAB);
        $$1.accept(Items.CHISELED_QUARTZ_BLOCK);
        $$1.accept(Items.QUARTZ_BRICKS);
        $$1.accept(Items.QUARTZ_PILLAR);
        $$1.accept(Items.SMOOTH_QUARTZ);
        $$1.accept(Items.SMOOTH_QUARTZ_STAIRS);
        $$1.accept(Items.SMOOTH_QUARTZ_SLAB);
        $$1.accept(Items.AMETHYST_BLOCK);
        $$1.accept(Items.COPPER_BLOCK);
        $$1.accept(Items.CUT_COPPER);
        $$1.accept(Items.CUT_COPPER_STAIRS);
        $$1.accept(Items.CUT_COPPER_SLAB);
        $$1.accept(Items.EXPOSED_COPPER);
        $$1.accept(Items.EXPOSED_CUT_COPPER);
        $$1.accept(Items.EXPOSED_CUT_COPPER_STAIRS);
        $$1.accept(Items.EXPOSED_CUT_COPPER_SLAB);
        $$1.accept(Items.WEATHERED_COPPER);
        $$1.accept(Items.WEATHERED_CUT_COPPER);
        $$1.accept(Items.WEATHERED_CUT_COPPER_STAIRS);
        $$1.accept(Items.WEATHERED_CUT_COPPER_SLAB);
        $$1.accept(Items.OXIDIZED_COPPER);
        $$1.accept(Items.OXIDIZED_CUT_COPPER);
        $$1.accept(Items.OXIDIZED_CUT_COPPER_STAIRS);
        $$1.accept(Items.OXIDIZED_CUT_COPPER_SLAB);
        $$1.accept(Items.WAXED_COPPER_BLOCK);
        $$1.accept(Items.WAXED_CUT_COPPER);
        $$1.accept(Items.WAXED_CUT_COPPER_STAIRS);
        $$1.accept(Items.WAXED_CUT_COPPER_SLAB);
        $$1.accept(Items.WAXED_EXPOSED_COPPER);
        $$1.accept(Items.WAXED_EXPOSED_CUT_COPPER);
        $$1.accept(Items.WAXED_EXPOSED_CUT_COPPER_STAIRS);
        $$1.accept(Items.WAXED_EXPOSED_CUT_COPPER_SLAB);
        $$1.accept(Items.WAXED_WEATHERED_COPPER);
        $$1.accept(Items.WAXED_WEATHERED_CUT_COPPER);
        $$1.accept(Items.WAXED_WEATHERED_CUT_COPPER_STAIRS);
        $$1.accept(Items.WAXED_WEATHERED_CUT_COPPER_SLAB);
        $$1.accept(Items.WAXED_OXIDIZED_COPPER);
        $$1.accept(Items.WAXED_OXIDIZED_CUT_COPPER);
        $$1.accept(Items.WAXED_OXIDIZED_CUT_COPPER_STAIRS);
        $$1.accept(Items.WAXED_OXIDIZED_CUT_COPPER_SLAB);
    }).build();
    private static final CreativeModeTab COLORED_BLOCKS = CreativeModeTab.builder(CreativeModeTab.Row.TOP, 1).title(Component.translatable("itemGroup.coloredBlocks")).icon((Supplier<ItemStack>)((Supplier)() -> new ItemStack(Blocks.CYAN_WOOL))).displayItems(($$0, $$1, $$2) -> {
        $$1.accept(Items.WHITE_WOOL);
        $$1.accept(Items.LIGHT_GRAY_WOOL);
        $$1.accept(Items.GRAY_WOOL);
        $$1.accept(Items.BLACK_WOOL);
        $$1.accept(Items.BROWN_WOOL);
        $$1.accept(Items.RED_WOOL);
        $$1.accept(Items.ORANGE_WOOL);
        $$1.accept(Items.YELLOW_WOOL);
        $$1.accept(Items.LIME_WOOL);
        $$1.accept(Items.GREEN_WOOL);
        $$1.accept(Items.CYAN_WOOL);
        $$1.accept(Items.LIGHT_BLUE_WOOL);
        $$1.accept(Items.BLUE_WOOL);
        $$1.accept(Items.PURPLE_WOOL);
        $$1.accept(Items.MAGENTA_WOOL);
        $$1.accept(Items.PINK_WOOL);
        $$1.accept(Items.WHITE_CARPET);
        $$1.accept(Items.LIGHT_GRAY_CARPET);
        $$1.accept(Items.GRAY_CARPET);
        $$1.accept(Items.BLACK_CARPET);
        $$1.accept(Items.BROWN_CARPET);
        $$1.accept(Items.RED_CARPET);
        $$1.accept(Items.ORANGE_CARPET);
        $$1.accept(Items.YELLOW_CARPET);
        $$1.accept(Items.LIME_CARPET);
        $$1.accept(Items.GREEN_CARPET);
        $$1.accept(Items.CYAN_CARPET);
        $$1.accept(Items.LIGHT_BLUE_CARPET);
        $$1.accept(Items.BLUE_CARPET);
        $$1.accept(Items.PURPLE_CARPET);
        $$1.accept(Items.MAGENTA_CARPET);
        $$1.accept(Items.PINK_CARPET);
        $$1.accept(Items.TERRACOTTA);
        $$1.accept(Items.WHITE_TERRACOTTA);
        $$1.accept(Items.LIGHT_GRAY_TERRACOTTA);
        $$1.accept(Items.GRAY_TERRACOTTA);
        $$1.accept(Items.BLACK_TERRACOTTA);
        $$1.accept(Items.BROWN_TERRACOTTA);
        $$1.accept(Items.RED_TERRACOTTA);
        $$1.accept(Items.ORANGE_TERRACOTTA);
        $$1.accept(Items.YELLOW_TERRACOTTA);
        $$1.accept(Items.LIME_TERRACOTTA);
        $$1.accept(Items.GREEN_TERRACOTTA);
        $$1.accept(Items.CYAN_TERRACOTTA);
        $$1.accept(Items.LIGHT_BLUE_TERRACOTTA);
        $$1.accept(Items.BLUE_TERRACOTTA);
        $$1.accept(Items.PURPLE_TERRACOTTA);
        $$1.accept(Items.MAGENTA_TERRACOTTA);
        $$1.accept(Items.PINK_TERRACOTTA);
        $$1.accept(Items.WHITE_CONCRETE);
        $$1.accept(Items.LIGHT_GRAY_CONCRETE);
        $$1.accept(Items.GRAY_CONCRETE);
        $$1.accept(Items.BLACK_CONCRETE);
        $$1.accept(Items.BROWN_CONCRETE);
        $$1.accept(Items.RED_CONCRETE);
        $$1.accept(Items.ORANGE_CONCRETE);
        $$1.accept(Items.YELLOW_CONCRETE);
        $$1.accept(Items.LIME_CONCRETE);
        $$1.accept(Items.GREEN_CONCRETE);
        $$1.accept(Items.CYAN_CONCRETE);
        $$1.accept(Items.LIGHT_BLUE_CONCRETE);
        $$1.accept(Items.BLUE_CONCRETE);
        $$1.accept(Items.PURPLE_CONCRETE);
        $$1.accept(Items.MAGENTA_CONCRETE);
        $$1.accept(Items.PINK_CONCRETE);
        $$1.accept(Items.WHITE_CONCRETE_POWDER);
        $$1.accept(Items.LIGHT_GRAY_CONCRETE_POWDER);
        $$1.accept(Items.GRAY_CONCRETE_POWDER);
        $$1.accept(Items.BLACK_CONCRETE_POWDER);
        $$1.accept(Items.BROWN_CONCRETE_POWDER);
        $$1.accept(Items.RED_CONCRETE_POWDER);
        $$1.accept(Items.ORANGE_CONCRETE_POWDER);
        $$1.accept(Items.YELLOW_CONCRETE_POWDER);
        $$1.accept(Items.LIME_CONCRETE_POWDER);
        $$1.accept(Items.GREEN_CONCRETE_POWDER);
        $$1.accept(Items.CYAN_CONCRETE_POWDER);
        $$1.accept(Items.LIGHT_BLUE_CONCRETE_POWDER);
        $$1.accept(Items.BLUE_CONCRETE_POWDER);
        $$1.accept(Items.PURPLE_CONCRETE_POWDER);
        $$1.accept(Items.MAGENTA_CONCRETE_POWDER);
        $$1.accept(Items.PINK_CONCRETE_POWDER);
        $$1.accept(Items.WHITE_GLAZED_TERRACOTTA);
        $$1.accept(Items.LIGHT_GRAY_GLAZED_TERRACOTTA);
        $$1.accept(Items.GRAY_GLAZED_TERRACOTTA);
        $$1.accept(Items.BLACK_GLAZED_TERRACOTTA);
        $$1.accept(Items.BROWN_GLAZED_TERRACOTTA);
        $$1.accept(Items.RED_GLAZED_TERRACOTTA);
        $$1.accept(Items.ORANGE_GLAZED_TERRACOTTA);
        $$1.accept(Items.YELLOW_GLAZED_TERRACOTTA);
        $$1.accept(Items.LIME_GLAZED_TERRACOTTA);
        $$1.accept(Items.GREEN_GLAZED_TERRACOTTA);
        $$1.accept(Items.CYAN_GLAZED_TERRACOTTA);
        $$1.accept(Items.LIGHT_BLUE_GLAZED_TERRACOTTA);
        $$1.accept(Items.BLUE_GLAZED_TERRACOTTA);
        $$1.accept(Items.PURPLE_GLAZED_TERRACOTTA);
        $$1.accept(Items.MAGENTA_GLAZED_TERRACOTTA);
        $$1.accept(Items.PINK_GLAZED_TERRACOTTA);
        $$1.accept(Items.GLASS);
        $$1.accept(Items.TINTED_GLASS);
        $$1.accept(Items.WHITE_STAINED_GLASS);
        $$1.accept(Items.LIGHT_GRAY_STAINED_GLASS);
        $$1.accept(Items.GRAY_STAINED_GLASS);
        $$1.accept(Items.BLACK_STAINED_GLASS);
        $$1.accept(Items.BROWN_STAINED_GLASS);
        $$1.accept(Items.RED_STAINED_GLASS);
        $$1.accept(Items.ORANGE_STAINED_GLASS);
        $$1.accept(Items.YELLOW_STAINED_GLASS);
        $$1.accept(Items.LIME_STAINED_GLASS);
        $$1.accept(Items.GREEN_STAINED_GLASS);
        $$1.accept(Items.CYAN_STAINED_GLASS);
        $$1.accept(Items.LIGHT_BLUE_STAINED_GLASS);
        $$1.accept(Items.BLUE_STAINED_GLASS);
        $$1.accept(Items.PURPLE_STAINED_GLASS);
        $$1.accept(Items.MAGENTA_STAINED_GLASS);
        $$1.accept(Items.PINK_STAINED_GLASS);
        $$1.accept(Items.GLASS_PANE);
        $$1.accept(Items.WHITE_STAINED_GLASS_PANE);
        $$1.accept(Items.LIGHT_GRAY_STAINED_GLASS_PANE);
        $$1.accept(Items.GRAY_STAINED_GLASS_PANE);
        $$1.accept(Items.BLACK_STAINED_GLASS_PANE);
        $$1.accept(Items.BROWN_STAINED_GLASS_PANE);
        $$1.accept(Items.RED_STAINED_GLASS_PANE);
        $$1.accept(Items.ORANGE_STAINED_GLASS_PANE);
        $$1.accept(Items.YELLOW_STAINED_GLASS_PANE);
        $$1.accept(Items.LIME_STAINED_GLASS_PANE);
        $$1.accept(Items.GREEN_STAINED_GLASS_PANE);
        $$1.accept(Items.CYAN_STAINED_GLASS_PANE);
        $$1.accept(Items.LIGHT_BLUE_STAINED_GLASS_PANE);
        $$1.accept(Items.BLUE_STAINED_GLASS_PANE);
        $$1.accept(Items.PURPLE_STAINED_GLASS_PANE);
        $$1.accept(Items.MAGENTA_STAINED_GLASS_PANE);
        $$1.accept(Items.PINK_STAINED_GLASS_PANE);
        $$1.accept(Items.SHULKER_BOX);
        $$1.accept(Items.WHITE_SHULKER_BOX);
        $$1.accept(Items.LIGHT_GRAY_SHULKER_BOX);
        $$1.accept(Items.GRAY_SHULKER_BOX);
        $$1.accept(Items.BLACK_SHULKER_BOX);
        $$1.accept(Items.BROWN_SHULKER_BOX);
        $$1.accept(Items.RED_SHULKER_BOX);
        $$1.accept(Items.ORANGE_SHULKER_BOX);
        $$1.accept(Items.YELLOW_SHULKER_BOX);
        $$1.accept(Items.LIME_SHULKER_BOX);
        $$1.accept(Items.GREEN_SHULKER_BOX);
        $$1.accept(Items.CYAN_SHULKER_BOX);
        $$1.accept(Items.LIGHT_BLUE_SHULKER_BOX);
        $$1.accept(Items.BLUE_SHULKER_BOX);
        $$1.accept(Items.PURPLE_SHULKER_BOX);
        $$1.accept(Items.MAGENTA_SHULKER_BOX);
        $$1.accept(Items.PINK_SHULKER_BOX);
        $$1.accept(Items.WHITE_BED);
        $$1.accept(Items.LIGHT_GRAY_BED);
        $$1.accept(Items.GRAY_BED);
        $$1.accept(Items.BLACK_BED);
        $$1.accept(Items.BROWN_BED);
        $$1.accept(Items.RED_BED);
        $$1.accept(Items.ORANGE_BED);
        $$1.accept(Items.YELLOW_BED);
        $$1.accept(Items.LIME_BED);
        $$1.accept(Items.GREEN_BED);
        $$1.accept(Items.CYAN_BED);
        $$1.accept(Items.LIGHT_BLUE_BED);
        $$1.accept(Items.BLUE_BED);
        $$1.accept(Items.PURPLE_BED);
        $$1.accept(Items.MAGENTA_BED);
        $$1.accept(Items.PINK_BED);
        $$1.accept(Items.CANDLE);
        $$1.accept(Items.WHITE_CANDLE);
        $$1.accept(Items.LIGHT_GRAY_CANDLE);
        $$1.accept(Items.GRAY_CANDLE);
        $$1.accept(Items.BLACK_CANDLE);
        $$1.accept(Items.BROWN_CANDLE);
        $$1.accept(Items.RED_CANDLE);
        $$1.accept(Items.ORANGE_CANDLE);
        $$1.accept(Items.YELLOW_CANDLE);
        $$1.accept(Items.LIME_CANDLE);
        $$1.accept(Items.GREEN_CANDLE);
        $$1.accept(Items.CYAN_CANDLE);
        $$1.accept(Items.LIGHT_BLUE_CANDLE);
        $$1.accept(Items.BLUE_CANDLE);
        $$1.accept(Items.PURPLE_CANDLE);
        $$1.accept(Items.MAGENTA_CANDLE);
        $$1.accept(Items.PINK_CANDLE);
        $$1.accept(Items.WHITE_BANNER);
        $$1.accept(Items.LIGHT_GRAY_BANNER);
        $$1.accept(Items.GRAY_BANNER);
        $$1.accept(Items.BLACK_BANNER);
        $$1.accept(Items.BROWN_BANNER);
        $$1.accept(Items.RED_BANNER);
        $$1.accept(Items.ORANGE_BANNER);
        $$1.accept(Items.YELLOW_BANNER);
        $$1.accept(Items.LIME_BANNER);
        $$1.accept(Items.GREEN_BANNER);
        $$1.accept(Items.CYAN_BANNER);
        $$1.accept(Items.LIGHT_BLUE_BANNER);
        $$1.accept(Items.BLUE_BANNER);
        $$1.accept(Items.PURPLE_BANNER);
        $$1.accept(Items.MAGENTA_BANNER);
        $$1.accept(Items.PINK_BANNER);
    }).build();
    private static final CreativeModeTab NATURAL_BLOCKS = CreativeModeTab.builder(CreativeModeTab.Row.TOP, 2).title(Component.translatable("itemGroup.natural")).icon((Supplier<ItemStack>)((Supplier)() -> new ItemStack(Blocks.GRASS_BLOCK))).displayItems(($$0, $$1, $$2) -> {
        $$1.accept(Items.GRASS_BLOCK);
        $$1.accept(Items.PODZOL);
        $$1.accept(Items.MYCELIUM);
        $$1.accept(Items.DIRT_PATH);
        $$1.accept(Items.DIRT);
        $$1.accept(Items.COARSE_DIRT);
        $$1.accept(Items.ROOTED_DIRT);
        $$1.accept(Items.FARMLAND);
        $$1.accept(Items.MUD);
        $$1.accept(Items.CLAY);
        $$1.accept(Items.GRAVEL);
        $$1.accept(Items.SAND);
        $$1.accept(Items.SANDSTONE);
        $$1.accept(Items.RED_SAND);
        $$1.accept(Items.RED_SANDSTONE);
        $$1.accept(Items.ICE);
        $$1.accept(Items.PACKED_ICE);
        $$1.accept(Items.BLUE_ICE);
        $$1.accept(Items.SNOW_BLOCK);
        $$1.accept(Items.SNOW);
        $$1.accept(Items.MOSS_BLOCK);
        $$1.accept(Items.MOSS_CARPET);
        $$1.accept(Items.STONE);
        $$1.accept(Items.DEEPSLATE);
        $$1.accept(Items.GRANITE);
        $$1.accept(Items.DIORITE);
        $$1.accept(Items.ANDESITE);
        $$1.accept(Items.CALCITE);
        $$1.accept(Items.TUFF);
        $$1.accept(Items.DRIPSTONE_BLOCK);
        $$1.accept(Items.POINTED_DRIPSTONE);
        $$1.accept(Items.PRISMARINE);
        $$1.accept(Items.MAGMA_BLOCK);
        $$1.accept(Items.OBSIDIAN);
        $$1.accept(Items.CRYING_OBSIDIAN);
        $$1.accept(Items.NETHERRACK);
        $$1.accept(Items.CRIMSON_NYLIUM);
        $$1.accept(Items.WARPED_NYLIUM);
        $$1.accept(Items.SOUL_SAND);
        $$1.accept(Items.SOUL_SOIL);
        $$1.accept(Items.BONE_BLOCK);
        $$1.accept(Items.BLACKSTONE);
        $$1.accept(Items.BASALT);
        $$1.accept(Items.SMOOTH_BASALT);
        $$1.accept(Items.END_STONE);
        $$1.accept(Items.COAL_ORE);
        $$1.accept(Items.DEEPSLATE_COAL_ORE);
        $$1.accept(Items.IRON_ORE);
        $$1.accept(Items.DEEPSLATE_IRON_ORE);
        $$1.accept(Items.COPPER_ORE);
        $$1.accept(Items.DEEPSLATE_COPPER_ORE);
        $$1.accept(Items.GOLD_ORE);
        $$1.accept(Items.DEEPSLATE_GOLD_ORE);
        $$1.accept(Items.REDSTONE_ORE);
        $$1.accept(Items.DEEPSLATE_REDSTONE_ORE);
        $$1.accept(Items.EMERALD_ORE);
        $$1.accept(Items.DEEPSLATE_EMERALD_ORE);
        $$1.accept(Items.LAPIS_ORE);
        $$1.accept(Items.DEEPSLATE_LAPIS_ORE);
        $$1.accept(Items.DIAMOND_ORE);
        $$1.accept(Items.DEEPSLATE_DIAMOND_ORE);
        $$1.accept(Items.NETHER_GOLD_ORE);
        $$1.accept(Items.NETHER_QUARTZ_ORE);
        $$1.accept(Items.ANCIENT_DEBRIS);
        $$1.accept(Items.RAW_IRON_BLOCK);
        $$1.accept(Items.RAW_COPPER_BLOCK);
        $$1.accept(Items.RAW_GOLD_BLOCK);
        $$1.accept(Items.GLOWSTONE);
        $$1.accept(Items.AMETHYST_BLOCK);
        $$1.accept(Items.BUDDING_AMETHYST);
        $$1.accept(Items.SMALL_AMETHYST_BUD);
        $$1.accept(Items.MEDIUM_AMETHYST_BUD);
        $$1.accept(Items.LARGE_AMETHYST_BUD);
        $$1.accept(Items.AMETHYST_CLUSTER);
        $$1.accept(Items.OAK_LOG);
        $$1.accept(Items.SPRUCE_LOG);
        $$1.accept(Items.BIRCH_LOG);
        $$1.accept(Items.JUNGLE_LOG);
        $$1.accept(Items.ACACIA_LOG);
        $$1.accept(Items.DARK_OAK_LOG);
        $$1.accept(Items.MANGROVE_LOG);
        $$1.accept(Items.MUSHROOM_STEM);
        $$1.accept(Items.CRIMSON_STEM);
        $$1.accept(Items.WARPED_STEM);
        $$1.accept(Items.OAK_LEAVES);
        $$1.accept(Items.SPRUCE_LEAVES);
        $$1.accept(Items.BIRCH_LEAVES);
        $$1.accept(Items.JUNGLE_LEAVES);
        $$1.accept(Items.ACACIA_LEAVES);
        $$1.accept(Items.DARK_OAK_LEAVES);
        $$1.accept(Items.MANGROVE_LEAVES);
        $$1.accept(Items.MANGROVE_ROOTS);
        $$1.accept(Items.MUDDY_MANGROVE_ROOTS);
        $$1.accept(Items.AZALEA_LEAVES);
        $$1.accept(Items.FLOWERING_AZALEA_LEAVES);
        $$1.accept(Items.BROWN_MUSHROOM_BLOCK);
        $$1.accept(Items.RED_MUSHROOM_BLOCK);
        $$1.accept(Items.NETHER_WART_BLOCK);
        $$1.accept(Items.WARPED_WART_BLOCK);
        $$1.accept(Items.SHROOMLIGHT);
        $$1.accept(Items.OAK_SAPLING);
        $$1.accept(Items.SPRUCE_SAPLING);
        $$1.accept(Items.BIRCH_SAPLING);
        $$1.accept(Items.JUNGLE_SAPLING);
        $$1.accept(Items.ACACIA_SAPLING);
        $$1.accept(Items.DARK_OAK_SAPLING);
        $$1.accept(Items.MANGROVE_PROPAGULE);
        $$1.accept(Items.AZALEA);
        $$1.accept(Items.FLOWERING_AZALEA);
        $$1.accept(Items.BROWN_MUSHROOM);
        $$1.accept(Items.RED_MUSHROOM);
        $$1.accept(Items.CRIMSON_FUNGUS);
        $$1.accept(Items.WARPED_FUNGUS);
        $$1.accept(Items.GRASS);
        $$1.accept(Items.FERN);
        $$1.accept(Items.DEAD_BUSH);
        $$1.accept(Items.DANDELION);
        $$1.accept(Items.POPPY);
        $$1.accept(Items.BLUE_ORCHID);
        $$1.accept(Items.ALLIUM);
        $$1.accept(Items.AZURE_BLUET);
        $$1.accept(Items.RED_TULIP);
        $$1.accept(Items.ORANGE_TULIP);
        $$1.accept(Items.WHITE_TULIP);
        $$1.accept(Items.PINK_TULIP);
        $$1.accept(Items.OXEYE_DAISY);
        $$1.accept(Items.CORNFLOWER);
        $$1.accept(Items.LILY_OF_THE_VALLEY);
        $$1.accept(Items.SPORE_BLOSSOM);
        $$1.accept(Items.BAMBOO);
        $$1.accept(Items.SUGAR_CANE);
        $$1.accept(Items.CACTUS);
        $$1.accept(Items.WITHER_ROSE);
        $$1.accept(Items.CRIMSON_ROOTS);
        $$1.accept(Items.WARPED_ROOTS);
        $$1.accept(Items.NETHER_SPROUTS);
        $$1.accept(Items.WEEPING_VINES);
        $$1.accept(Items.TWISTING_VINES);
        $$1.accept(Items.VINE);
        $$1.accept(Items.TALL_GRASS);
        $$1.accept(Items.LARGE_FERN);
        $$1.accept(Items.SUNFLOWER);
        $$1.accept(Items.LILAC);
        $$1.accept(Items.ROSE_BUSH);
        $$1.accept(Items.PEONY);
        $$1.accept(Items.BIG_DRIPLEAF);
        $$1.accept(Items.SMALL_DRIPLEAF);
        $$1.accept(Items.CHORUS_PLANT);
        $$1.accept(Items.CHORUS_FLOWER);
        $$1.accept(Items.GLOW_LICHEN);
        $$1.accept(Items.HANGING_ROOTS);
        $$1.accept(Items.FROGSPAWN);
        $$1.accept(Items.TURTLE_EGG);
        $$1.accept(Items.WHEAT_SEEDS);
        $$1.accept(Items.COCOA_BEANS);
        $$1.accept(Items.PUMPKIN_SEEDS);
        $$1.accept(Items.MELON_SEEDS);
        $$1.accept(Items.BEETROOT_SEEDS);
        $$1.accept(Items.GLOW_BERRIES);
        $$1.accept(Items.SWEET_BERRIES);
        $$1.accept(Items.NETHER_WART);
        $$1.accept(Items.LILY_PAD);
        $$1.accept(Items.SEAGRASS);
        $$1.accept(Items.SEA_PICKLE);
        $$1.accept(Items.KELP);
        $$1.accept(Items.DRIED_KELP_BLOCK);
        $$1.accept(Items.TUBE_CORAL_BLOCK);
        $$1.accept(Items.BRAIN_CORAL_BLOCK);
        $$1.accept(Items.BUBBLE_CORAL_BLOCK);
        $$1.accept(Items.FIRE_CORAL_BLOCK);
        $$1.accept(Items.HORN_CORAL_BLOCK);
        $$1.accept(Items.DEAD_TUBE_CORAL_BLOCK);
        $$1.accept(Items.DEAD_BRAIN_CORAL_BLOCK);
        $$1.accept(Items.DEAD_BUBBLE_CORAL_BLOCK);
        $$1.accept(Items.DEAD_FIRE_CORAL_BLOCK);
        $$1.accept(Items.DEAD_HORN_CORAL_BLOCK);
        $$1.accept(Items.TUBE_CORAL);
        $$1.accept(Items.BRAIN_CORAL);
        $$1.accept(Items.BUBBLE_CORAL);
        $$1.accept(Items.FIRE_CORAL);
        $$1.accept(Items.HORN_CORAL);
        $$1.accept(Items.DEAD_BRAIN_CORAL);
        $$1.accept(Items.DEAD_BUBBLE_CORAL);
        $$1.accept(Items.DEAD_FIRE_CORAL);
        $$1.accept(Items.DEAD_HORN_CORAL);
        $$1.accept(Items.DEAD_TUBE_CORAL);
        $$1.accept(Items.TUBE_CORAL_FAN);
        $$1.accept(Items.BRAIN_CORAL_FAN);
        $$1.accept(Items.BUBBLE_CORAL_FAN);
        $$1.accept(Items.FIRE_CORAL_FAN);
        $$1.accept(Items.HORN_CORAL_FAN);
        $$1.accept(Items.DEAD_TUBE_CORAL_FAN);
        $$1.accept(Items.DEAD_BRAIN_CORAL_FAN);
        $$1.accept(Items.DEAD_BUBBLE_CORAL_FAN);
        $$1.accept(Items.DEAD_FIRE_CORAL_FAN);
        $$1.accept(Items.DEAD_HORN_CORAL_FAN);
        $$1.accept(Items.SPONGE);
        $$1.accept(Items.WET_SPONGE);
        $$1.accept(Items.MELON);
        $$1.accept(Items.PUMPKIN);
        $$1.accept(Items.CARVED_PUMPKIN);
        $$1.accept(Items.JACK_O_LANTERN);
        $$1.accept(Items.HAY_BLOCK);
        $$1.accept(Items.BEE_NEST);
        $$1.accept(Items.HONEYCOMB_BLOCK);
        $$1.accept(Items.SLIME_BLOCK);
        $$1.accept(Items.HONEY_BLOCK);
        $$1.accept(Items.OCHRE_FROGLIGHT);
        $$1.accept(Items.VERDANT_FROGLIGHT);
        $$1.accept(Items.PEARLESCENT_FROGLIGHT);
        $$1.accept(Items.SCULK);
        $$1.accept(Items.SCULK_VEIN);
        $$1.accept(Items.SCULK_CATALYST);
        $$1.accept(Items.SCULK_SHRIEKER);
        $$1.accept(Items.SCULK_SENSOR);
        $$1.accept(Items.COBWEB);
        $$1.accept(Items.BEDROCK);
    }).build();
    private static final CreativeModeTab FUNCTIONAL_BLOCKS = CreativeModeTab.builder(CreativeModeTab.Row.TOP, 3).title(Component.translatable("itemGroup.functional")).icon((Supplier<ItemStack>)((Supplier)() -> new ItemStack(Items.OAK_SIGN))).displayItems(($$0, $$1, $$2) -> {
        $$1.accept(Items.TORCH);
        $$1.accept(Items.SOUL_TORCH);
        $$1.accept(Items.REDSTONE_TORCH);
        $$1.accept(Items.LANTERN);
        $$1.accept(Items.SOUL_LANTERN);
        $$1.accept(Items.CHAIN);
        $$1.accept(Items.END_ROD);
        $$1.accept(Items.SEA_LANTERN);
        $$1.accept(Items.REDSTONE_LAMP);
        $$1.accept(Items.GLOWSTONE);
        $$1.accept(Items.SHROOMLIGHT);
        $$1.accept(Items.OCHRE_FROGLIGHT);
        $$1.accept(Items.VERDANT_FROGLIGHT);
        $$1.accept(Items.PEARLESCENT_FROGLIGHT);
        $$1.accept(Items.CRYING_OBSIDIAN);
        $$1.accept(Items.GLOW_LICHEN);
        $$1.accept(Items.MAGMA_BLOCK);
        $$1.accept(Items.CRAFTING_TABLE);
        $$1.accept(Items.STONECUTTER);
        $$1.accept(Items.CARTOGRAPHY_TABLE);
        $$1.accept(Items.FLETCHING_TABLE);
        $$1.accept(Items.SMITHING_TABLE);
        $$1.accept(Items.GRINDSTONE);
        $$1.accept(Items.LOOM);
        $$1.accept(Items.FURNACE);
        $$1.accept(Items.SMOKER);
        $$1.accept(Items.BLAST_FURNACE);
        $$1.accept(Items.CAMPFIRE);
        $$1.accept(Items.SOUL_CAMPFIRE);
        $$1.accept(Items.ANVIL);
        $$1.accept(Items.CHIPPED_ANVIL);
        $$1.accept(Items.DAMAGED_ANVIL);
        $$1.accept(Items.COMPOSTER);
        $$1.accept(Items.NOTE_BLOCK);
        $$1.accept(Items.JUKEBOX);
        $$1.accept(Items.ENCHANTING_TABLE);
        $$1.accept(Items.END_CRYSTAL);
        $$1.accept(Items.BREWING_STAND);
        $$1.accept(Items.CAULDRON);
        $$1.accept(Items.BELL);
        $$1.accept(Items.BEACON);
        $$1.accept(Items.CONDUIT);
        $$1.accept(Items.LODESTONE);
        $$1.accept(Items.LADDER);
        $$1.accept(Items.SCAFFOLDING);
        $$1.accept(Items.BEE_NEST);
        $$1.accept(Items.BEEHIVE);
        $$1.accept(Items.LIGHTNING_ROD);
        $$1.accept(Items.FLOWER_POT);
        $$1.accept(Items.ARMOR_STAND);
        $$1.accept(Items.ITEM_FRAME);
        $$1.accept(Items.GLOW_ITEM_FRAME);
        $$1.accept(Items.PAINTING);
        $$1.accept(Items.BOOKSHELF);
        $$1.accept(Items.CHISELED_BOOKSHELF);
        $$1.accept(Items.LECTERN);
        $$1.accept(Items.TINTED_GLASS);
        $$1.accept(Items.OAK_SIGN);
        $$1.accept(Items.OAK_HANGING_SIGN);
        $$1.accept(Items.SPRUCE_SIGN);
        $$1.accept(Items.SPRUCE_HANGING_SIGN);
        $$1.accept(Items.BIRCH_SIGN);
        $$1.accept(Items.BIRCH_HANGING_SIGN);
        $$1.accept(Items.JUNGLE_SIGN);
        $$1.accept(Items.JUNGLE_HANGING_SIGN);
        $$1.accept(Items.ACACIA_SIGN);
        $$1.accept(Items.ACACIA_HANGING_SIGN);
        $$1.accept(Items.DARK_OAK_SIGN);
        $$1.accept(Items.DARK_OAK_HANGING_SIGN);
        $$1.accept(Items.MANGROVE_SIGN);
        $$1.accept(Items.MANGROVE_HANGING_SIGN);
        $$1.accept(Items.BAMBOO_SIGN);
        $$1.accept(Items.BAMBOO_HANGING_SIGN);
        $$1.accept(Items.CRIMSON_SIGN);
        $$1.accept(Items.CRIMSON_HANGING_SIGN);
        $$1.accept(Items.WARPED_SIGN);
        $$1.accept(Items.WARPED_HANGING_SIGN);
        $$1.accept(Items.CHEST);
        $$1.accept(Items.BARREL);
        $$1.accept(Items.ENDER_CHEST);
        $$1.accept(Items.SHULKER_BOX);
        $$1.accept(Items.WHITE_SHULKER_BOX);
        $$1.accept(Items.LIGHT_GRAY_SHULKER_BOX);
        $$1.accept(Items.GRAY_SHULKER_BOX);
        $$1.accept(Items.BLACK_SHULKER_BOX);
        $$1.accept(Items.BROWN_SHULKER_BOX);
        $$1.accept(Items.RED_SHULKER_BOX);
        $$1.accept(Items.ORANGE_SHULKER_BOX);
        $$1.accept(Items.YELLOW_SHULKER_BOX);
        $$1.accept(Items.LIME_SHULKER_BOX);
        $$1.accept(Items.GREEN_SHULKER_BOX);
        $$1.accept(Items.CYAN_SHULKER_BOX);
        $$1.accept(Items.LIGHT_BLUE_SHULKER_BOX);
        $$1.accept(Items.BLUE_SHULKER_BOX);
        $$1.accept(Items.PURPLE_SHULKER_BOX);
        $$1.accept(Items.MAGENTA_SHULKER_BOX);
        $$1.accept(Items.PINK_SHULKER_BOX);
        $$1.accept(Items.RESPAWN_ANCHOR);
        $$1.accept(Items.WHITE_BED);
        $$1.accept(Items.LIGHT_GRAY_BED);
        $$1.accept(Items.GRAY_BED);
        $$1.accept(Items.BLACK_BED);
        $$1.accept(Items.BROWN_BED);
        $$1.accept(Items.RED_BED);
        $$1.accept(Items.ORANGE_BED);
        $$1.accept(Items.YELLOW_BED);
        $$1.accept(Items.LIME_BED);
        $$1.accept(Items.GREEN_BED);
        $$1.accept(Items.CYAN_BED);
        $$1.accept(Items.LIGHT_BLUE_BED);
        $$1.accept(Items.BLUE_BED);
        $$1.accept(Items.PURPLE_BED);
        $$1.accept(Items.MAGENTA_BED);
        $$1.accept(Items.PINK_BED);
        $$1.accept(Items.CANDLE);
        $$1.accept(Items.WHITE_CANDLE);
        $$1.accept(Items.LIGHT_GRAY_CANDLE);
        $$1.accept(Items.GRAY_CANDLE);
        $$1.accept(Items.BLACK_CANDLE);
        $$1.accept(Items.BROWN_CANDLE);
        $$1.accept(Items.RED_CANDLE);
        $$1.accept(Items.ORANGE_CANDLE);
        $$1.accept(Items.YELLOW_CANDLE);
        $$1.accept(Items.LIME_CANDLE);
        $$1.accept(Items.GREEN_CANDLE);
        $$1.accept(Items.CYAN_CANDLE);
        $$1.accept(Items.LIGHT_BLUE_CANDLE);
        $$1.accept(Items.BLUE_CANDLE);
        $$1.accept(Items.PURPLE_CANDLE);
        $$1.accept(Items.MAGENTA_CANDLE);
        $$1.accept(Items.PINK_CANDLE);
        $$1.accept(Items.WHITE_BANNER);
        $$1.accept(Items.LIGHT_GRAY_BANNER);
        $$1.accept(Items.GRAY_BANNER);
        $$1.accept(Items.BLACK_BANNER);
        $$1.accept(Items.BROWN_BANNER);
        $$1.accept(Items.RED_BANNER);
        $$1.accept(Items.ORANGE_BANNER);
        $$1.accept(Items.YELLOW_BANNER);
        $$1.accept(Items.LIME_BANNER);
        $$1.accept(Items.GREEN_BANNER);
        $$1.accept(Items.CYAN_BANNER);
        $$1.accept(Items.LIGHT_BLUE_BANNER);
        $$1.accept(Items.BLUE_BANNER);
        $$1.accept(Items.PURPLE_BANNER);
        $$1.accept(Items.MAGENTA_BANNER);
        $$1.accept(Items.PINK_BANNER);
        $$1.accept(Raid.getLeaderBannerInstance());
        $$1.accept(Items.SKELETON_SKULL);
        $$1.accept(Items.WITHER_SKELETON_SKULL);
        $$1.accept(Items.PLAYER_HEAD);
        $$1.accept(Items.ZOMBIE_HEAD);
        $$1.accept(Items.CREEPER_HEAD);
        $$1.accept(Items.PIGLIN_HEAD);
        $$1.accept(Items.DRAGON_HEAD);
        $$1.accept(Items.DRAGON_EGG);
        $$1.accept(Items.END_PORTAL_FRAME);
        $$1.accept(Items.ENDER_EYE);
        $$1.accept(Items.INFESTED_STONE);
        $$1.accept(Items.INFESTED_COBBLESTONE);
        $$1.accept(Items.INFESTED_STONE_BRICKS);
        $$1.accept(Items.INFESTED_MOSSY_STONE_BRICKS);
        $$1.accept(Items.INFESTED_CRACKED_STONE_BRICKS);
        $$1.accept(Items.INFESTED_CHISELED_STONE_BRICKS);
        $$1.accept(Items.INFESTED_DEEPSLATE);
    }).build();
    private static final CreativeModeTab REDSTONE_BLOCKS = CreativeModeTab.builder(CreativeModeTab.Row.TOP, 4).title(Component.translatable("itemGroup.redstone")).icon((Supplier<ItemStack>)((Supplier)() -> new ItemStack(Items.REDSTONE))).displayItems(($$0, $$1, $$2) -> {
        $$1.accept(Items.REDSTONE);
        $$1.accept(Items.REDSTONE_TORCH);
        $$1.accept(Items.REDSTONE_BLOCK);
        $$1.accept(Items.REPEATER);
        $$1.accept(Items.COMPARATOR);
        $$1.accept(Items.TARGET);
        $$1.accept(Items.LEVER);
        $$1.accept(Items.OAK_BUTTON);
        $$1.accept(Items.STONE_BUTTON);
        $$1.accept(Items.OAK_PRESSURE_PLATE);
        $$1.accept(Items.STONE_PRESSURE_PLATE);
        $$1.accept(Items.LIGHT_WEIGHTED_PRESSURE_PLATE);
        $$1.accept(Items.HEAVY_WEIGHTED_PRESSURE_PLATE);
        $$1.accept(Items.SCULK_SENSOR);
        $$1.accept(Items.WHITE_WOOL);
        $$1.accept(Items.TRIPWIRE_HOOK);
        $$1.accept(Items.STRING);
        $$1.accept(Items.LECTERN);
        $$1.accept(Items.DAYLIGHT_DETECTOR);
        $$1.accept(Items.LIGHTNING_ROD);
        $$1.accept(Items.PISTON);
        $$1.accept(Items.STICKY_PISTON);
        $$1.accept(Items.SLIME_BLOCK);
        $$1.accept(Items.HONEY_BLOCK);
        $$1.accept(Items.DISPENSER);
        $$1.accept(Items.DROPPER);
        $$1.accept(Items.HOPPER);
        $$1.accept(Items.CHEST);
        $$1.accept(Items.BARREL);
        $$1.accept(Items.CHISELED_BOOKSHELF);
        $$1.accept(Items.FURNACE);
        $$1.accept(Items.TRAPPED_CHEST);
        $$1.accept(Items.OBSERVER);
        $$1.accept(Items.NOTE_BLOCK);
        $$1.accept(Items.COMPOSTER);
        $$1.accept(Items.CAULDRON);
        $$1.accept(Items.RAIL);
        $$1.accept(Items.POWERED_RAIL);
        $$1.accept(Items.DETECTOR_RAIL);
        $$1.accept(Items.ACTIVATOR_RAIL);
        $$1.accept(Items.MINECART);
        $$1.accept(Items.HOPPER_MINECART);
        $$1.accept(Items.CHEST_MINECART);
        $$1.accept(Items.FURNACE_MINECART);
        $$1.accept(Items.TNT_MINECART);
        $$1.accept(Items.OAK_CHEST_BOAT);
        $$1.accept(Items.BAMBOO_CHEST_RAFT);
        $$1.accept(Items.OAK_DOOR);
        $$1.accept(Items.IRON_DOOR);
        $$1.accept(Items.OAK_FENCE_GATE);
        $$1.accept(Items.OAK_TRAPDOOR);
        $$1.accept(Items.IRON_TRAPDOOR);
        $$1.accept(Items.TNT);
        $$1.accept(Items.REDSTONE_LAMP);
        $$1.accept(Items.BELL);
        $$1.accept(Items.BIG_DRIPLEAF);
        $$1.accept(Items.ARMOR_STAND);
        $$1.accept(Items.REDSTONE_ORE);
    }).build();
    private static final CreativeModeTab HOTBAR = CreativeModeTab.builder(CreativeModeTab.Row.TOP, 5).title(Component.translatable("itemGroup.hotbar")).icon((Supplier<ItemStack>)((Supplier)() -> new ItemStack(Blocks.BOOKSHELF))).alignedRight().type(CreativeModeTab.Type.HOTBAR).build();
    private static final CreativeModeTab SEARCH = CreativeModeTab.builder(CreativeModeTab.Row.TOP, 6).title(Component.translatable("itemGroup.search")).icon((Supplier<ItemStack>)((Supplier)() -> new ItemStack(Items.COMPASS))).displayItems(($$0, $$1, $$2) -> {
        Set<ItemStack> $$3 = ItemStackLinkedSet.createTypeAndTagSet();
        for (CreativeModeTab $$4 : TABS) {
            if ($$4.getType() == CreativeModeTab.Type.SEARCH) continue;
            $$3.addAll($$4.getSearchTabDisplayItems());
        }
        $$1.acceptAll((Collection<ItemStack>)$$3);
    }).backgroundSuffix("item_search.png").alignedRight().type(CreativeModeTab.Type.SEARCH).build();
    private static final CreativeModeTab TOOLS_AND_UTILITIES = CreativeModeTab.builder(CreativeModeTab.Row.BOTTOM, 0).title(Component.translatable("itemGroup.tools")).icon((Supplier<ItemStack>)((Supplier)() -> new ItemStack(Items.DIAMOND_PICKAXE))).displayItems(($$0, $$1, $$2) -> {
        $$1.accept(Items.WOODEN_SHOVEL);
        $$1.accept(Items.WOODEN_PICKAXE);
        $$1.accept(Items.WOODEN_AXE);
        $$1.accept(Items.WOODEN_HOE);
        $$1.accept(Items.STONE_SHOVEL);
        $$1.accept(Items.STONE_PICKAXE);
        $$1.accept(Items.STONE_AXE);
        $$1.accept(Items.STONE_HOE);
        $$1.accept(Items.IRON_SHOVEL);
        $$1.accept(Items.IRON_PICKAXE);
        $$1.accept(Items.IRON_AXE);
        $$1.accept(Items.IRON_HOE);
        $$1.accept(Items.GOLDEN_SHOVEL);
        $$1.accept(Items.GOLDEN_PICKAXE);
        $$1.accept(Items.GOLDEN_AXE);
        $$1.accept(Items.GOLDEN_HOE);
        $$1.accept(Items.DIAMOND_SHOVEL);
        $$1.accept(Items.DIAMOND_PICKAXE);
        $$1.accept(Items.DIAMOND_AXE);
        $$1.accept(Items.DIAMOND_HOE);
        $$1.accept(Items.NETHERITE_SHOVEL);
        $$1.accept(Items.NETHERITE_PICKAXE);
        $$1.accept(Items.NETHERITE_AXE);
        $$1.accept(Items.NETHERITE_HOE);
        $$1.accept(Items.BUCKET);
        $$1.accept(Items.WATER_BUCKET);
        $$1.accept(Items.PUFFERFISH_BUCKET);
        $$1.accept(Items.SALMON_BUCKET);
        $$1.accept(Items.COD_BUCKET);
        $$1.accept(Items.TROPICAL_FISH_BUCKET);
        $$1.accept(Items.AXOLOTL_BUCKET);
        $$1.accept(Items.TADPOLE_BUCKET);
        $$1.accept(Items.LAVA_BUCKET);
        $$1.accept(Items.POWDER_SNOW_BUCKET);
        $$1.accept(Items.MILK_BUCKET);
        $$1.accept(Items.FISHING_ROD);
        $$1.accept(Items.FLINT_AND_STEEL);
        $$1.accept(Items.FIRE_CHARGE);
        $$1.accept(Items.BONE_MEAL);
        $$1.accept(Items.SHEARS);
        $$1.accept(Items.NAME_TAG);
        $$1.accept(Items.LEAD);
        if ($$0.contains(FeatureFlags.BUNDLE)) {
            $$1.accept(Items.BUNDLE);
        }
        $$1.accept(Items.COMPASS);
        $$1.accept(Items.RECOVERY_COMPASS);
        $$1.accept(Items.CLOCK);
        $$1.accept(Items.SPYGLASS);
        $$1.accept(Items.MAP);
        $$1.accept(Items.WRITABLE_BOOK);
        $$1.accept(Items.ENDER_PEARL);
        $$1.accept(Items.ENDER_EYE);
        $$1.accept(Items.ELYTRA);
        CreativeModeTabs.generateFireworksAllDurations($$1, CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
        $$1.accept(Items.SADDLE);
        $$1.accept(Items.CARROT_ON_A_STICK);
        $$1.accept(Items.WARPED_FUNGUS_ON_A_STICK);
        $$1.accept(Items.OAK_BOAT);
        $$1.accept(Items.OAK_CHEST_BOAT);
        $$1.accept(Items.SPRUCE_BOAT);
        $$1.accept(Items.SPRUCE_CHEST_BOAT);
        $$1.accept(Items.BIRCH_BOAT);
        $$1.accept(Items.BIRCH_CHEST_BOAT);
        $$1.accept(Items.JUNGLE_BOAT);
        $$1.accept(Items.JUNGLE_CHEST_BOAT);
        $$1.accept(Items.ACACIA_BOAT);
        $$1.accept(Items.ACACIA_CHEST_BOAT);
        $$1.accept(Items.DARK_OAK_BOAT);
        $$1.accept(Items.DARK_OAK_CHEST_BOAT);
        $$1.accept(Items.MANGROVE_BOAT);
        $$1.accept(Items.MANGROVE_CHEST_BOAT);
        $$1.accept(Items.BAMBOO_RAFT);
        $$1.accept(Items.BAMBOO_CHEST_RAFT);
        $$1.accept(Items.RAIL);
        $$1.accept(Items.POWERED_RAIL);
        $$1.accept(Items.DETECTOR_RAIL);
        $$1.accept(Items.ACTIVATOR_RAIL);
        $$1.accept(Items.MINECART);
        $$1.accept(Items.HOPPER_MINECART);
        $$1.accept(Items.CHEST_MINECART);
        $$1.accept(Items.FURNACE_MINECART);
        $$1.accept(Items.TNT_MINECART);
        CreativeModeTabs.generateInstrumentTypes($$1, Items.GOAT_HORN, InstrumentTags.GOAT_HORNS, CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
        $$1.accept(Items.MUSIC_DISC_13);
        $$1.accept(Items.MUSIC_DISC_CAT);
        $$1.accept(Items.MUSIC_DISC_BLOCKS);
        $$1.accept(Items.MUSIC_DISC_CHIRP);
        $$1.accept(Items.MUSIC_DISC_FAR);
        $$1.accept(Items.MUSIC_DISC_MALL);
        $$1.accept(Items.MUSIC_DISC_MELLOHI);
        $$1.accept(Items.MUSIC_DISC_STAL);
        $$1.accept(Items.MUSIC_DISC_STRAD);
        $$1.accept(Items.MUSIC_DISC_WARD);
        $$1.accept(Items.MUSIC_DISC_11);
        $$1.accept(Items.MUSIC_DISC_WAIT);
        $$1.accept(Items.MUSIC_DISC_OTHERSIDE);
        $$1.accept(Items.MUSIC_DISC_5);
        $$1.accept(Items.MUSIC_DISC_PIGSTEP);
    }).build();
    private static final CreativeModeTab COMBAT = CreativeModeTab.builder(CreativeModeTab.Row.BOTTOM, 1).title(Component.translatable("itemGroup.combat")).icon((Supplier<ItemStack>)((Supplier)() -> new ItemStack(Items.NETHERITE_SWORD))).displayItems(($$0, $$1, $$2) -> {
        $$1.accept(Items.WOODEN_SWORD);
        $$1.accept(Items.STONE_SWORD);
        $$1.accept(Items.IRON_SWORD);
        $$1.accept(Items.GOLDEN_SWORD);
        $$1.accept(Items.DIAMOND_SWORD);
        $$1.accept(Items.NETHERITE_SWORD);
        $$1.accept(Items.WOODEN_AXE);
        $$1.accept(Items.STONE_AXE);
        $$1.accept(Items.IRON_AXE);
        $$1.accept(Items.GOLDEN_AXE);
        $$1.accept(Items.DIAMOND_AXE);
        $$1.accept(Items.NETHERITE_AXE);
        $$1.accept(Items.TRIDENT);
        $$1.accept(Items.SHIELD);
        $$1.accept(Items.LEATHER_HELMET);
        $$1.accept(Items.LEATHER_CHESTPLATE);
        $$1.accept(Items.LEATHER_LEGGINGS);
        $$1.accept(Items.LEATHER_BOOTS);
        $$1.accept(Items.CHAINMAIL_HELMET);
        $$1.accept(Items.CHAINMAIL_CHESTPLATE);
        $$1.accept(Items.CHAINMAIL_LEGGINGS);
        $$1.accept(Items.CHAINMAIL_BOOTS);
        $$1.accept(Items.IRON_HELMET);
        $$1.accept(Items.IRON_CHESTPLATE);
        $$1.accept(Items.IRON_LEGGINGS);
        $$1.accept(Items.IRON_BOOTS);
        $$1.accept(Items.GOLDEN_HELMET);
        $$1.accept(Items.GOLDEN_CHESTPLATE);
        $$1.accept(Items.GOLDEN_LEGGINGS);
        $$1.accept(Items.GOLDEN_BOOTS);
        $$1.accept(Items.DIAMOND_HELMET);
        $$1.accept(Items.DIAMOND_CHESTPLATE);
        $$1.accept(Items.DIAMOND_LEGGINGS);
        $$1.accept(Items.DIAMOND_BOOTS);
        $$1.accept(Items.NETHERITE_HELMET);
        $$1.accept(Items.NETHERITE_CHESTPLATE);
        $$1.accept(Items.NETHERITE_LEGGINGS);
        $$1.accept(Items.NETHERITE_BOOTS);
        $$1.accept(Items.TURTLE_HELMET);
        $$1.accept(Items.LEATHER_HORSE_ARMOR);
        $$1.accept(Items.IRON_HORSE_ARMOR);
        $$1.accept(Items.GOLDEN_HORSE_ARMOR);
        $$1.accept(Items.DIAMOND_HORSE_ARMOR);
        $$1.accept(Items.TOTEM_OF_UNDYING);
        $$1.accept(Items.TNT);
        $$1.accept(Items.END_CRYSTAL);
        $$1.accept(Items.SNOWBALL);
        $$1.accept(Items.EGG);
        $$1.accept(Items.BOW);
        $$1.accept(Items.CROSSBOW);
        CreativeModeTabs.generateFireworksAllDurations($$1, CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
        $$1.accept(Items.ARROW);
        $$1.accept(Items.SPECTRAL_ARROW);
        CreativeModeTabs.generatePotionEffectTypes($$1, Items.TIPPED_ARROW, CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
    }).build();
    private static final CreativeModeTab FOOD_AND_DRINKS = CreativeModeTab.builder(CreativeModeTab.Row.BOTTOM, 2).title(Component.translatable("itemGroup.foodAndDrink")).icon((Supplier<ItemStack>)((Supplier)() -> new ItemStack(Items.GOLDEN_APPLE))).displayItems(($$0, $$1, $$2) -> {
        $$1.accept(Items.APPLE);
        $$1.accept(Items.GOLDEN_APPLE);
        $$1.accept(Items.ENCHANTED_GOLDEN_APPLE);
        $$1.accept(Items.MELON_SLICE);
        $$1.accept(Items.SWEET_BERRIES);
        $$1.accept(Items.GLOW_BERRIES);
        $$1.accept(Items.CHORUS_FRUIT);
        $$1.accept(Items.CARROT);
        $$1.accept(Items.GOLDEN_CARROT);
        $$1.accept(Items.POTATO);
        $$1.accept(Items.BAKED_POTATO);
        $$1.accept(Items.POISONOUS_POTATO);
        $$1.accept(Items.BEETROOT);
        $$1.accept(Items.DRIED_KELP);
        $$1.accept(Items.BEEF);
        $$1.accept(Items.COOKED_BEEF);
        $$1.accept(Items.PORKCHOP);
        $$1.accept(Items.COOKED_PORKCHOP);
        $$1.accept(Items.MUTTON);
        $$1.accept(Items.COOKED_MUTTON);
        $$1.accept(Items.CHICKEN);
        $$1.accept(Items.COOKED_CHICKEN);
        $$1.accept(Items.RABBIT);
        $$1.accept(Items.COOKED_RABBIT);
        $$1.accept(Items.COD);
        $$1.accept(Items.COOKED_COD);
        $$1.accept(Items.SALMON);
        $$1.accept(Items.COOKED_SALMON);
        $$1.accept(Items.TROPICAL_FISH);
        $$1.accept(Items.PUFFERFISH);
        $$1.accept(Items.BREAD);
        $$1.accept(Items.COOKIE);
        $$1.accept(Items.CAKE);
        $$1.accept(Items.PUMPKIN_PIE);
        $$1.accept(Items.ROTTEN_FLESH);
        $$1.accept(Items.SPIDER_EYE);
        $$1.accept(Items.MUSHROOM_STEW);
        $$1.accept(Items.BEETROOT_SOUP);
        $$1.accept(Items.RABBIT_STEW);
        CreativeModeTabs.generateSuspiciousStews($$1, CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
        $$1.accept(Items.MILK_BUCKET);
        $$1.accept(Items.HONEY_BOTTLE);
        CreativeModeTabs.generatePotionEffectTypes($$1, Items.POTION, CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
        CreativeModeTabs.generatePotionEffectTypes($$1, Items.SPLASH_POTION, CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
        CreativeModeTabs.generatePotionEffectTypes($$1, Items.LINGERING_POTION, CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
    }).build();
    private static final CreativeModeTab INGREDIENTS = CreativeModeTab.builder(CreativeModeTab.Row.BOTTOM, 3).title(Component.translatable("itemGroup.ingredients")).icon((Supplier<ItemStack>)((Supplier)() -> new ItemStack(Items.IRON_INGOT))).displayItems(($$0, $$1, $$2) -> {
        $$1.accept(Items.COAL);
        $$1.accept(Items.CHARCOAL);
        $$1.accept(Items.RAW_IRON);
        $$1.accept(Items.RAW_COPPER);
        $$1.accept(Items.RAW_GOLD);
        $$1.accept(Items.EMERALD);
        $$1.accept(Items.LAPIS_LAZULI);
        $$1.accept(Items.DIAMOND);
        $$1.accept(Items.ANCIENT_DEBRIS);
        $$1.accept(Items.QUARTZ);
        $$1.accept(Items.AMETHYST_SHARD);
        $$1.accept(Items.IRON_NUGGET);
        $$1.accept(Items.GOLD_NUGGET);
        $$1.accept(Items.IRON_INGOT);
        $$1.accept(Items.COPPER_INGOT);
        $$1.accept(Items.GOLD_INGOT);
        $$1.accept(Items.NETHERITE_SCRAP);
        $$1.accept(Items.NETHERITE_INGOT);
        $$1.accept(Items.STICK);
        $$1.accept(Items.FLINT);
        $$1.accept(Items.WHEAT);
        $$1.accept(Items.BONE);
        $$1.accept(Items.BONE_MEAL);
        $$1.accept(Items.STRING);
        $$1.accept(Items.FEATHER);
        $$1.accept(Items.SNOWBALL);
        $$1.accept(Items.EGG);
        $$1.accept(Items.LEATHER);
        $$1.accept(Items.RABBIT_HIDE);
        $$1.accept(Items.HONEYCOMB);
        $$1.accept(Items.INK_SAC);
        $$1.accept(Items.GLOW_INK_SAC);
        $$1.accept(Items.SCUTE);
        $$1.accept(Items.SLIME_BALL);
        $$1.accept(Items.CLAY_BALL);
        $$1.accept(Items.PRISMARINE_SHARD);
        $$1.accept(Items.PRISMARINE_CRYSTALS);
        $$1.accept(Items.NAUTILUS_SHELL);
        $$1.accept(Items.HEART_OF_THE_SEA);
        $$1.accept(Items.BLAZE_ROD);
        $$1.accept(Items.NETHER_STAR);
        $$1.accept(Items.ENDER_PEARL);
        $$1.accept(Items.ENDER_EYE);
        $$1.accept(Items.SHULKER_SHELL);
        $$1.accept(Items.POPPED_CHORUS_FRUIT);
        $$1.accept(Items.ECHO_SHARD);
        $$1.accept(Items.DISC_FRAGMENT_5);
        $$1.accept(Items.WHITE_DYE);
        $$1.accept(Items.LIGHT_GRAY_DYE);
        $$1.accept(Items.GRAY_DYE);
        $$1.accept(Items.BLACK_DYE);
        $$1.accept(Items.BROWN_DYE);
        $$1.accept(Items.RED_DYE);
        $$1.accept(Items.ORANGE_DYE);
        $$1.accept(Items.YELLOW_DYE);
        $$1.accept(Items.LIME_DYE);
        $$1.accept(Items.GREEN_DYE);
        $$1.accept(Items.CYAN_DYE);
        $$1.accept(Items.LIGHT_BLUE_DYE);
        $$1.accept(Items.BLUE_DYE);
        $$1.accept(Items.PURPLE_DYE);
        $$1.accept(Items.MAGENTA_DYE);
        $$1.accept(Items.PINK_DYE);
        $$1.accept(Items.BOWL);
        $$1.accept(Items.BRICK);
        $$1.accept(Items.NETHER_BRICK);
        $$1.accept(Items.PAPER);
        $$1.accept(Items.BOOK);
        $$1.accept(Items.FIREWORK_STAR);
        $$1.accept(Items.GLASS_BOTTLE);
        $$1.accept(Items.NETHER_WART);
        $$1.accept(Items.REDSTONE);
        $$1.accept(Items.GLOWSTONE_DUST);
        $$1.accept(Items.GUNPOWDER);
        $$1.accept(Items.DRAGON_BREATH);
        $$1.accept(Items.FERMENTED_SPIDER_EYE);
        $$1.accept(Items.BLAZE_POWDER);
        $$1.accept(Items.SUGAR);
        $$1.accept(Items.RABBIT_FOOT);
        $$1.accept(Items.GLISTERING_MELON_SLICE);
        $$1.accept(Items.SPIDER_EYE);
        $$1.accept(Items.PUFFERFISH);
        $$1.accept(Items.MAGMA_CREAM);
        $$1.accept(Items.GOLDEN_CARROT);
        $$1.accept(Items.GHAST_TEAR);
        $$1.accept(Items.TURTLE_HELMET);
        $$1.accept(Items.PHANTOM_MEMBRANE);
        $$1.accept(Items.FLOWER_BANNER_PATTERN);
        $$1.accept(Items.CREEPER_BANNER_PATTERN);
        $$1.accept(Items.SKULL_BANNER_PATTERN);
        $$1.accept(Items.MOJANG_BANNER_PATTERN);
        $$1.accept(Items.GLOBE_BANNER_PATTERN);
        $$1.accept(Items.PIGLIN_BANNER_PATTERN);
        $$1.accept(Items.NETHERITE_UPGRADE_SMITHING_TEMPLATE);
        $$1.accept(Items.SENTRY_ARMOR_TRIM_SMITHING_TEMPLATE);
        $$1.accept(Items.DUNE_ARMOR_TRIM_SMITHING_TEMPLATE);
        $$1.accept(Items.COAST_ARMOR_TRIM_SMITHING_TEMPLATE);
        $$1.accept(Items.WILD_ARMOR_TRIM_SMITHING_TEMPLATE);
        $$1.accept(Items.WARD_ARMOR_TRIM_SMITHING_TEMPLATE);
        $$1.accept(Items.EYE_ARMOR_TRIM_SMITHING_TEMPLATE);
        $$1.accept(Items.VEX_ARMOR_TRIM_SMITHING_TEMPLATE);
        $$1.accept(Items.TIDE_ARMOR_TRIM_SMITHING_TEMPLATE);
        $$1.accept(Items.SNOUT_ARMOR_TRIM_SMITHING_TEMPLATE);
        $$1.accept(Items.RIB_ARMOR_TRIM_SMITHING_TEMPLATE);
        $$1.accept(Items.SPIRE_ARMOR_TRIM_SMITHING_TEMPLATE);
        $$1.accept(Items.EXPERIENCE_BOTTLE);
        EnumSet $$3 = EnumSet.allOf(EnchantmentCategory.class);
        CreativeModeTabs.generateEnchantmentBookTypesOnlyMaxLevel($$1, (Set<EnchantmentCategory>)$$3, CreativeModeTab.TabVisibility.PARENT_TAB_ONLY);
        CreativeModeTabs.generateEnchantmentBookTypesAllLevels($$1, (Set<EnchantmentCategory>)$$3, CreativeModeTab.TabVisibility.SEARCH_TAB_ONLY);
    }).build();
    private static final CreativeModeTab SPAWN_EGGS = CreativeModeTab.builder(CreativeModeTab.Row.BOTTOM, 4).title(Component.translatable("itemGroup.spawnEggs")).icon((Supplier<ItemStack>)((Supplier)() -> new ItemStack(Items.PIG_SPAWN_EGG))).displayItems(($$0, $$1, $$2) -> {
        $$1.accept(Items.SPAWNER);
        $$1.accept(Items.ALLAY_SPAWN_EGG);
        $$1.accept(Items.AXOLOTL_SPAWN_EGG);
        $$1.accept(Items.BAT_SPAWN_EGG);
        $$1.accept(Items.BEE_SPAWN_EGG);
        $$1.accept(Items.BLAZE_SPAWN_EGG);
        $$1.accept(Items.CAMEL_SPAWN_EGG);
        $$1.accept(Items.CAT_SPAWN_EGG);
        $$1.accept(Items.CAVE_SPIDER_SPAWN_EGG);
        $$1.accept(Items.CHICKEN_SPAWN_EGG);
        $$1.accept(Items.COD_SPAWN_EGG);
        $$1.accept(Items.COW_SPAWN_EGG);
        $$1.accept(Items.CREEPER_SPAWN_EGG);
        $$1.accept(Items.DOLPHIN_SPAWN_EGG);
        $$1.accept(Items.DONKEY_SPAWN_EGG);
        $$1.accept(Items.DROWNED_SPAWN_EGG);
        $$1.accept(Items.ELDER_GUARDIAN_SPAWN_EGG);
        $$1.accept(Items.ENDERMAN_SPAWN_EGG);
        $$1.accept(Items.ENDERMITE_SPAWN_EGG);
        $$1.accept(Items.EVOKER_SPAWN_EGG);
        $$1.accept(Items.FOX_SPAWN_EGG);
        $$1.accept(Items.FROG_SPAWN_EGG);
        $$1.accept(Items.GHAST_SPAWN_EGG);
        $$1.accept(Items.GLOW_SQUID_SPAWN_EGG);
        $$1.accept(Items.GOAT_SPAWN_EGG);
        $$1.accept(Items.GUARDIAN_SPAWN_EGG);
        $$1.accept(Items.HOGLIN_SPAWN_EGG);
        $$1.accept(Items.HORSE_SPAWN_EGG);
        $$1.accept(Items.HUSK_SPAWN_EGG);
        $$1.accept(Items.IRON_GOLEM_SPAWN_EGG);
        $$1.accept(Items.LLAMA_SPAWN_EGG);
        $$1.accept(Items.MAGMA_CUBE_SPAWN_EGG);
        $$1.accept(Items.MOOSHROOM_SPAWN_EGG);
        $$1.accept(Items.MULE_SPAWN_EGG);
        $$1.accept(Items.OCELOT_SPAWN_EGG);
        $$1.accept(Items.PANDA_SPAWN_EGG);
        $$1.accept(Items.PARROT_SPAWN_EGG);
        $$1.accept(Items.PHANTOM_SPAWN_EGG);
        $$1.accept(Items.PIG_SPAWN_EGG);
        $$1.accept(Items.PIGLIN_SPAWN_EGG);
        $$1.accept(Items.PIGLIN_BRUTE_SPAWN_EGG);
        $$1.accept(Items.PILLAGER_SPAWN_EGG);
        $$1.accept(Items.POLAR_BEAR_SPAWN_EGG);
        $$1.accept(Items.PUFFERFISH_SPAWN_EGG);
        $$1.accept(Items.RABBIT_SPAWN_EGG);
        $$1.accept(Items.RAVAGER_SPAWN_EGG);
        $$1.accept(Items.SALMON_SPAWN_EGG);
        $$1.accept(Items.SHEEP_SPAWN_EGG);
        $$1.accept(Items.SHULKER_SPAWN_EGG);
        $$1.accept(Items.SILVERFISH_SPAWN_EGG);
        $$1.accept(Items.SKELETON_SPAWN_EGG);
        $$1.accept(Items.SKELETON_HORSE_SPAWN_EGG);
        $$1.accept(Items.SLIME_SPAWN_EGG);
        $$1.accept(Items.SNOW_GOLEM_SPAWN_EGG);
        $$1.accept(Items.SPIDER_SPAWN_EGG);
        $$1.accept(Items.SQUID_SPAWN_EGG);
        $$1.accept(Items.STRAY_SPAWN_EGG);
        $$1.accept(Items.STRIDER_SPAWN_EGG);
        $$1.accept(Items.TADPOLE_SPAWN_EGG);
        $$1.accept(Items.TRADER_LLAMA_SPAWN_EGG);
        $$1.accept(Items.TROPICAL_FISH_SPAWN_EGG);
        $$1.accept(Items.TURTLE_SPAWN_EGG);
        $$1.accept(Items.VEX_SPAWN_EGG);
        $$1.accept(Items.VILLAGER_SPAWN_EGG);
        $$1.accept(Items.VINDICATOR_SPAWN_EGG);
        $$1.accept(Items.WANDERING_TRADER_SPAWN_EGG);
        $$1.accept(Items.WARDEN_SPAWN_EGG);
        $$1.accept(Items.WITCH_SPAWN_EGG);
        $$1.accept(Items.WITHER_SKELETON_SPAWN_EGG);
        $$1.accept(Items.WOLF_SPAWN_EGG);
        $$1.accept(Items.ZOGLIN_SPAWN_EGG);
        $$1.accept(Items.ZOMBIE_SPAWN_EGG);
        $$1.accept(Items.ZOMBIE_HORSE_SPAWN_EGG);
        $$1.accept(Items.ZOMBIE_VILLAGER_SPAWN_EGG);
        $$1.accept(Items.ZOMBIFIED_PIGLIN_SPAWN_EGG);
    }).build();
    private static final CreativeModeTab OP_BLOCKS = CreativeModeTab.builder(CreativeModeTab.Row.BOTTOM, 5).title(Component.translatable("itemGroup.op")).icon((Supplier<ItemStack>)((Supplier)() -> new ItemStack(Items.COMMAND_BLOCK))).alignedRight().displayItems(($$0, $$1, $$2) -> {
        if ($$2) {
            $$1.accept(Items.COMMAND_BLOCK);
            $$1.accept(Items.CHAIN_COMMAND_BLOCK);
            $$1.accept(Items.REPEATING_COMMAND_BLOCK);
            $$1.accept(Items.COMMAND_BLOCK_MINECART);
            $$1.accept(Items.JIGSAW);
            $$1.accept(Items.STRUCTURE_BLOCK);
            $$1.accept(Items.STRUCTURE_VOID);
            $$1.accept(Items.BARRIER);
            $$1.accept(Items.DEBUG_STICK);
            for (int $$3 = 15; $$3 >= 0; --$$3) {
                $$1.accept(LightBlock.setLightOnStack(new ItemStack(Items.LIGHT), $$3));
            }
        }
    }).build();
    private static final CreativeModeTab INVENTORY = CreativeModeTab.builder(CreativeModeTab.Row.BOTTOM, 6).title(Component.translatable("itemGroup.inventory")).icon((Supplier<ItemStack>)((Supplier)() -> new ItemStack(Blocks.CHEST))).backgroundSuffix("inventory.png").hideTitle().alignedRight().type(CreativeModeTab.Type.INVENTORY).noScrollBar().build();
    private static final List<CreativeModeTab> TABS = CreativeModeTabs.checkTabs(BUILDING_BLOCKS, COLORED_BLOCKS, NATURAL_BLOCKS, FUNCTIONAL_BLOCKS, REDSTONE_BLOCKS, HOTBAR, SEARCH, TOOLS_AND_UTILITIES, COMBAT, FOOD_AND_DRINKS, INGREDIENTS, SPAWN_EGGS, OP_BLOCKS, INVENTORY);
    @Nullable
    public static FeatureFlagSet CACHED_ENABLED_FEATURES;
    public static boolean CACHED_HAS_PERMISSIONS;

    private static List<CreativeModeTab> checkTabs(CreativeModeTab ... $$0) {
        HashMap $$1 = new HashMap();
        for (CreativeModeTab $$2 : $$0) {
            String $$3 = $$2.getDisplayName().getString();
            String $$4 = (String)$$1.put((Object)Pair.of((Object)((Object)$$2.row()), (Object)$$2.column()), (Object)$$3);
            if ($$4 == null) continue;
            throw new IllegalArgumentException("Duplicate position: " + $$3 + " vs. " + $$4);
        }
        return List.of((Object[])$$0);
    }

    public static CreativeModeTab getDefaultTab() {
        return BUILDING_BLOCKS;
    }

    private static void generatePotionEffectTypes(CreativeModeTab.Output $$0, Item $$1, CreativeModeTab.TabVisibility $$2) {
        for (Potion $$3 : BuiltInRegistries.POTION) {
            if ($$3 == Potions.EMPTY) continue;
            $$0.accept(PotionUtils.setPotion(new ItemStack($$1), $$3), $$2);
        }
    }

    private static void generateEnchantmentBookTypesOnlyMaxLevel(CreativeModeTab.Output $$0, Set<EnchantmentCategory> $$1, CreativeModeTab.TabVisibility $$2) {
        for (Enchantment $$3 : BuiltInRegistries.ENCHANTMENT) {
            if (!$$1.contains((Object)$$3.category)) continue;
            $$0.accept(EnchantedBookItem.createForEnchantment(new EnchantmentInstance($$3, $$3.getMaxLevel())), $$2);
        }
    }

    private static void generateEnchantmentBookTypesAllLevels(CreativeModeTab.Output $$0, Set<EnchantmentCategory> $$1, CreativeModeTab.TabVisibility $$2) {
        for (Enchantment $$3 : BuiltInRegistries.ENCHANTMENT) {
            if (!$$1.contains((Object)$$3.category)) continue;
            for (int $$4 = $$3.getMinLevel(); $$4 <= $$3.getMaxLevel(); ++$$4) {
                $$0.accept(EnchantedBookItem.createForEnchantment(new EnchantmentInstance($$3, $$4)), $$2);
            }
        }
    }

    private static void generateInstrumentTypes(CreativeModeTab.Output $$0, Item $$1, TagKey<Instrument> $$2, CreativeModeTab.TabVisibility $$3) {
        for (Holder $$4 : BuiltInRegistries.INSTRUMENT.getTagOrEmpty($$2)) {
            $$0.accept(InstrumentItem.create($$1, $$4), $$3);
        }
    }

    private static void generateSuspiciousStews(CreativeModeTab.Output $$0, CreativeModeTab.TabVisibility $$1) {
        List<SuspiciousEffectHolder> $$2 = SuspiciousEffectHolder.getAllEffectHolders();
        Set<ItemStack> $$3 = ItemStackLinkedSet.createTypeAndTagSet();
        for (SuspiciousEffectHolder $$4 : $$2) {
            ItemStack $$5 = new ItemStack(Items.SUSPICIOUS_STEW);
            SuspiciousStewItem.saveMobEffect($$5, $$4.getSuspiciousEffect(), $$4.getEffectDuration());
            $$3.add((Object)$$5);
        }
        $$0.acceptAll((Collection<ItemStack>)$$3, $$1);
    }

    private static void generateFireworksAllDurations(CreativeModeTab.Output $$0, CreativeModeTab.TabVisibility $$1) {
        for (byte $$2 : FireworkRocketItem.CRAFTABLE_DURATIONS) {
            ItemStack $$3 = new ItemStack(Items.FIREWORK_ROCKET);
            FireworkRocketItem.setDuration($$3, $$2);
            $$0.accept($$3, $$1);
        }
    }

    public static List<CreativeModeTab> tabs() {
        return TABS.stream().filter(CreativeModeTab::shouldDisplay).toList();
    }

    public static List<CreativeModeTab> allTabs() {
        return TABS;
    }

    public static CreativeModeTab searchTab() {
        return SEARCH;
    }

    private static void buildAllTabContents(FeatureFlagSet $$02, boolean $$1) {
        TABS.stream().filter($$0 -> $$0.getType() == CreativeModeTab.Type.CATEGORY).forEach($$2 -> $$2.buildContents($$02, $$1));
        TABS.stream().filter($$0 -> $$0.getType() != CreativeModeTab.Type.CATEGORY).forEach($$2 -> $$2.buildContents($$02, $$1));
    }

    private static boolean wouldRebuildSameContents(FeatureFlagSet $$0, boolean $$1) {
        return CACHED_HAS_PERMISSIONS == $$1 && $$0.equals(CACHED_ENABLED_FEATURES);
    }

    public static boolean tryRebuildTabContents(FeatureFlagSet $$0, boolean $$1) {
        if (CreativeModeTabs.wouldRebuildSameContents($$0, $$1)) {
            return false;
        }
        CACHED_ENABLED_FEATURES = $$0;
        CACHED_HAS_PERMISSIONS = $$1;
        CreativeModeTabs.buildAllTabContents(CACHED_ENABLED_FEATURES, CACHED_HAS_PERMISSIONS);
        return true;
    }

    static {
        CACHED_HAS_PERMISSIONS = false;
    }
}